apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "ithome_crawler.fullname" .  | replace "_" "-" }}
spec:
  schedule: "{{ .Values.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 8 }}
          {{- end }}

          containers:
          - name: {{ .Chart.Name | replace "_" "-" }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command:
            - scrapy
            - crawl
            - ithome
            env:
              - name: MONGO_HOST
                value: {{ .Values.env.mongo.host }}
              - name: MONGO_DB
                value: {{ .Values.env.mongo.db }}
          restartPolicy: Never

