version: "2"
services:
  crawler:
    image: ghcr.io/ben4932042/ithome-crawler/scrapy:main
    container_name: ithome_crawler
    hostname: ithome_crawler  
    command: "scrapy crawl ithome"
    environment:
      - MONGO_HOST="mongodb://mongo:27017"
      - MONGO_DB="ithome_ironman"
  mongo:
    image: mongo
    container_name: mongodb
    hostname: mongodb
    restart: always
    ports:
      - "27017:27017"      